version: "3"
services:
  app:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    #   args:
    #     - DATABASE_URL=${DATABASE_URL}
    #     - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    #     - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    #     - NAVER_ID=${NAVER_ID}
    #     - NAVER_SECRET=${NAVER_SECRET}
    #     - NEXTAUTH_URL=${NEXTAUTH_URL}
    #     - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    image: hangakim/keyword_finder:latest
    ports:
      - "3000:80"
    env_file:
      - .env
