version: "3"
services:
  app:
    image: hangakim/keyword_finder:latest
    ports:
      - "3000:80"
    env_file:
      - .env
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app
