services:
  app:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    #   args:
    #     - DATABASE_URL=${DATABASE_URL}
    #     - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    #     - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    #     - NAVER_ID=${NAVER_ID}
    #     - NAVER_SECRET=${NAVER_SECRET}
    #     - NEXTAUTH_URL=${NEXTAUTH_URL}
    #     - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    image: hangakim/keyword_finder:latest
    # ports:
    #   - "3000:3000" # 컨테이너의 80 포트를 호스트의 80 포트로 매핑
    env_file:
      - .env
    # expose:
    #   - "3000" # 네트워크 내부에서 접근 가능하도록 설정

  nginx:
    # image: hangakim/keyword_finder:latest
    build: ./nginx
    # build:
    #   context: .
    #   dockerfile: ./nginx/Dockerfile
    depends_on:
      - app
    ports:
      - "80:80"
# 이것은 환경 변수를 제공한 후 convert-nginx.sh 파일을 nginx.conf 파일로 구문 분석하기 위한 것입니다.
# 다른 환경에서 결과 nginx.conf 파일을 가져옵니다.
# 또한 deployment.yml 파일에 kubernetes 특정 환경 변수를 제공합니다.
