import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import { SnackbarProvider } from "./_context/SnackbarContext";
import TopAppBar from "./_components/TopAppBar";
import { ThemeProvider } from "@mui/material/styles";
import { getServerAuthSession } from "~/server/auth";
import theme from "~/theme";
import SimpleBottomNavigation from "./_components/BottonNavi";

export const metadata: Metadata = {
  title: "Keyword Finder",
  description: "Generated by HangA",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await getServerAuthSession();
  return (
    <html lang="en">
      <body className={GeistSans.className} style={{ background: "#EFDFCC" }}>
        <TRPCReactProvider>
          <SnackbarProvider>
            <ThemeProvider theme={theme}>
              <TopAppBar session={session} />
              {children}
              <SimpleBottomNavigation />
            </ThemeProvider>
          </SnackbarProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
