import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import { SnackbarProvider } from "./_context/SnackbarContext";
import TopAppBar from "./_components/TopAppBar";
import { ThemeProvider } from "@mui/material/styles";
import { getServerAuthSession } from "~/server/auth";
import theme from "~/theme";
import SimpleBottomNavigation from "./_components/BottonNavi";
import { Box } from "@mui/material";
import { bgColor } from "~/styles/colors";

export const metadata: Metadata = {
  title: "Keyword Finder",
  description: "Generated by HangA",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await getServerAuthSession();
  return (
    <html lang="en">
      <body className={GeistSans.className} style={{ background: bgColor }}>
        <TRPCReactProvider>
          <SnackbarProvider>
            <ThemeProvider theme={theme}>
              <TopAppBar session={session} />
              <Box
                sx={{
                  paddingTop: { xs: "55px", sm: "70px" },
                  paddingBottom: { xs: "50px" },
                  minHeight: "100vh",
                  display: "flex",
                  flexDirection: "column",
                }}
              >
                <main style={{ flex: 1 }}>{children}</main>
                <SimpleBottomNavigation />
              </Box>
            </ThemeProvider>
          </SnackbarProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
